---
sidebar: sidebar 
permalink: solutions/fsxn-burst-to-cloud.html 
keywords: bluexp automation catalog, netapp automation solutions, fsx for ontap, burst to cloud 
summary: 您可以使用此自動化解決方案來為 NetApp ONTAP 提供 Amazon FSX 、其中包含 Volume 和相關的 FlexCache 。 
---
= Amazon FSX for NetApp ONTAP - 點到雲端
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用此自動化解決方案來為 NetApp ONTAP 提供 Amazon FSX 、其中包含 Volume 和相關的 FlexCache 。


NOTE: Amazon FSX for NetApp ONTAP 也稱為「 * 適用於 ONTAP * 的 FSX 」。

.關於本解決方案
本解決方案所提供的自動化程式碼可在較高層級執行下列動作：

* 為 ONTAP 檔案系統配置目的地 FSX
* 為檔案系統佈建儲存虛擬機器（ SVM ）
* 在來源和目的地系統之間建立叢集對等關係
* 在 FlexCache 的來源系統和目的地系統之間建立 SVM 對等關係
* 您也可以選擇使用適用於 ONTAP 的 FSX 建立 FlexVol Volume
* 在適用於 ONTAP 的 FSX 中建立 FlexCache Volume 、來源指向內部儲存設備


自動化是以 Docker 和 Docker Compose 為基礎、必須安裝在 Linux 虛擬機器上、如下所述。

.開始之前
您必須具備下列條件才能完成資源配置與組態：

* 您需要透過 BlueXP  Web UI 下載 https://console.bluexp.netapp.com/automationCatalog["Amazon FSX for NetApp ONTAP - 點到雲端"^]自動化解決方案。解決方案打包爲 file `AWS_FSxN_BTC.zip`。
* 來源與目的地系統之間的網路連線。
* 具有下列特性的 Linux VM ：
+
** 以 Debian 為基礎的 Linux 套裝作業系統
** 部署在用於 FSX 以進行 ONTAP 資源配置的同一 VPC 子集上


* AWS 帳戶。




== 步驟 1 ：安裝及設定 Docker

在以 Debian 為基礎的 Linux 虛擬機器中安裝及設定 Docker 。

.步驟
. 準備好環境。
+
[source, cli]
----
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
----
. 安裝 Docker 並驗證安裝。
+
[source, cli]
----
sudo apt-get install docker-ce docker-ce-cli containerd.io
docker --version
----
. 將所需的 Linux 群組與相關的使用者一起新增。
+
請先檢查 Linux 系統中是否存在 * 泊塢視窗 * 群組。如果沒有、請建立群組並新增使用者。根據預設、目前的 Shell 使用者會新增至群組。

+
[source, cli]
----
sudo groupadd docker
sudo usermod -aG docker $(whoami)
----
. 啟動新的群組和使用者定義
+
如果您與使用者一起建立新群組、則需要啟動定義。若要這麼做、您可以先登出 Linux 、然後再重新登入。或者、您也可以執行下列命令。

+
[source, cli]
----
newgrp docker
----




== 步驟 2 ：安裝 Docker Compose

在以 Debian 為基礎的 Linux 虛擬機器中安裝 Docker Compose 。

.步驟
. 安裝 Docker Compose 。
+
[source, cli]
----
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
----
. 確認安裝成功。
+
[source, cli]
----
docker-compose --version
----




== 步驟 3 ：準備 Docker 映像檔

您需要擷取並載入自動化解決方案隨附的 Docker 映像。

.步驟
. 將解決方案檔案複製 `AWS_FSxN_BTC.zip`到執行自動化程式碼的虛擬機器。
+
[source, cli]
----
scp -i ~/<private-key.pem> -r AWS_FSxN_BTC.zip user@<IP_ADDRESS_OF_VM>
----
+
輸入參數 `private-key.pem`是用於 AWS 虛擬機器驗證（ EC2 執行個體）的私密金鑰檔案。

. 使用解決方案檔案瀏覽至正確的資料夾、然後解壓縮檔案。
+
[source, cli]
----
unzip AWS_FSxN_BTC.zip
----
. 瀏覽至以解壓縮作業建立的新資料夾 `AWS_FSxN_BTC`、並列出檔案。您應該會看到 file `aws_fsxn_flexcache_image_latest.tar.gz`。
+
[source, cli]
----
ls -la
----
. 載入 Docker 映像檔。負載作業通常應在數秒內完成。
+
[source, cli]
----
docker load -i aws_fsxn_flexcache_image_latest.tar.gz
----
. 確認已載入 Docker 映像。
+
[source, cli]
----
docker images
----
+
您應該會看到帶有標記的 `latest` Docker 映像 `aws_fsxn_flexcache_image`。

+
[listing]
----
   REPOSITORY              TAG     IMAGE ID      CREATED      SIZE
aws_fsxn_flexcahce_image  latest  ay98y7853769  2 weeks ago  1.19GB
----




== 步驟 4 ：建立 AWS 認證的環境檔案

您必須使用存取和秘密金鑰來建立驗證的本機變數檔案。然後將檔案新增至 `.env`檔案。

.步驟
. 在下列位置建立 `awsauth.env`檔案：
+
`path/to/env-file/awsauth.env`

. 將下列內容新增至檔案：
+
[listing]
----
access_key=<>
secret_key=<>
----
+
格式 *must * 與上述所示完全相同，且與 `value`之間沒有任何空格 `key`。

. 使用變數將絕對檔案路徑新增至 `.env`檔案 `AWS_CREDS`。例如：
+
`AWS_CREDS=path/to/env-file/awsauth.env`





== 步驟 5 ：建立外部磁碟區

您需要外部磁碟區、以確保 Terraform 狀態檔案和其他重要檔案持續存在。這些檔案必須可供 Terraform 執行工作流程和部署。

.步驟
. 在 Docker Compose 之外建立外部 Volume 。
+
執行命令之前、請務必將 Volume 名稱（最後參數）更新為適當的值。

+
[source, cli]
----
docker volume create aws_fsxn_volume
----
. 使用命令將外部磁碟區的路徑新增至 `.env`環境檔案：
+
`PERSISTENT_VOL=path/to/external/volume:/volume_name`

+
請記得保留現有的檔案內容和結腸格式。例如：

+
[source, cli]
----
PERSISTENT_VOL=aws_fsxn_volume:/aws_fsxn_flexcache
----
+
您可以改用下列命令、將 NFS 共用新增為外部磁碟區：

+
`PERSISTENT_VOL=nfs/mnt/document:/aws_fsx_flexcache`

. 更新 Terraform 變數。
+
.. 瀏覽至資料夾 `aws_fsxn_variables`。
.. 確認存在以下兩個檔案： `terraform.tfvars`和 `variables.tf`。
.. 視環境需求更新中的值 `terraform.tfvars`。
+
如需詳細資訊、請參閱 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_file_system["Terraform 資源： ONTAP 檔案系統"^] 。







== 步驟 6 ：為 NetApp ONTAP 和 FlexCache 配置 Amazon FSX

您可以為 NetApp ONTAP 和 FlexCache 配置 Amazon FSX 。

.步驟
. 瀏覽至資料夾根目錄（ AWS_FSXN_BTC ）、然後發出資源配置命令。
+
[source, cli]
----
docker-compose -f docker-compose-provision.yml up
----
+
此命令會建立兩個容器。第一個容器會部署適用於 ONTAP 的 FSX 、第二個容器則會建立叢集對等關係、 SVM 對等關係、目的地 Volume 和 FlexCache 。

. 監控資源配置程序。
+
[source, cli]
----
docker-compose -f docker-compose-provision.yml logs -f
----
+
此命令可即時提供輸出，但已設定為透過檔案擷取記錄 `deployment.log`。您可以通過編輯文件和更新變量 `DEPLOYMENT_LOGS`來更改這些日誌文件的名稱 `.env`。





== 步驟 7 ：銷毀 Amazon FSX for NetApp ONTAP 和 FlexCache

您可以選擇性地刪除和移除 Amazon FSX for NetApp ONTAP 和 FlexCache 。

. 將檔案中的 `terraform.tfvars`變數設 `flexcache_operation`為「銷毀」。
. 瀏覽至資料夾根目錄（ AWS_FSXN_BTC ）、然後發出下列命令。
+
[source, cli]
----
docker-compose -f docker-compose-destroy.yml up
----
+
此命令會建立兩個容器。第一個容器會刪除 FlexCache 、第二個容器則會刪除 ONTAP 的 FSX 。

. 監控資源配置程序。
+
[source, cli]
----
docker-compose -f docker-compose-destroy.yml logs -f
----

